name: Node CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-greet-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run greet app
        run: node index.js

      # --- SNYK SCAN ---
      - name: Run Snyk Security Scan
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # --- SONARCLOUD SCAN ---
      - name: Install Sonar Scanner
        run: npm install -g sonar-scanner

      - name: Run SonarCloud Analysis
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
